// import { Product } from '../models/product.model';

// export const PRODUCTS: Product[] = [
//   {
//     id: '1',
//     name: 'Silk Saree',
//     price: 2500,
//     images: [
//       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS87TgjtlFiSZqYCXbh_glI92ikggPmj6k-aA&s',
//     ],
//     category: 'Saree',
//     colors: ['Red', 'Green', 'Blue'],
//     sizes: [],
//     description:
//       'Elegant silk saree with rich embroidery for festive occasions.',
//     inStock: true,
//   },
//   {
//     id: '2',
//     name: 'Cotton Shirt',
//     price: 799,
//     images: [
//       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBRWEZcn2NtJPLGHh62yAOKyHjhSkZ9CFfA&s',
//     ],
//     category: 'Shirt',
//     colors: ['White', 'Blue', 'Black'],
//     sizes: ['S', 'M', 'L', 'XL'],
//     description:
//       'Comfortable cotton shirt, perfect for office and casual wear.',
//     inStock: true,
//   },
//   {
//     id: '3',
//     name: 'Kids Party Wear',
//     price: 1200,
//     images: [
//       'https://www.kidsbee.in/wp-content/uploads/2023/06/kids-birthday-frock-party-wear.jpg',
//     ],
//     category: 'Kids',
//     colors: ['Pink', 'Yellow'],
//     sizes: ['2Y', '4Y', '6Y'],
//     description: 'Trendy kids party wear outfit made with premium fabric.',
//     inStock: false,
//   },
//   {
//     id: '4',
//     name: 'Custom Fabric',
//     price: 450,
//     images: [
//       'https://imagedigital.com.au/wp-content/uploads/2020/01/custom-fabric-print.jpg',
//     ],
//     category: 'Fabric',
//     colors: ['Brown', 'Grey'],
//     sizes: [],
//     description: 'Custom fabrics sold per meter. Soft & durable.',
//     inStock: true,
//   },
// ];

import { Product } from '../models/product.model';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Silk Saree',
    price: 2500,
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS87TgjtlFiSZqYCXbh_glI92ikggPmj6k-aA&s',
    ],
    category: 'Saree',
    colors: ['Red', 'Green', 'Blue'],
    sizes: [],
    description:
      'Elegant silk saree with rich embroidery for festive occasions.',
    inStock: true,
  },
  {
    id: '2',
    name: 'Cotton Shirt',
    price: 799,
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBRWEZcn2NtJPLGHh62yAOKyHjhSkZ9CFfA&s',
    ],
    category: 'Shirt',
    colors: ['White', 'Blue', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    description:
      'Comfortable cotton shirt, perfect for office and casual wear.',
    inStock: true,
  },
  {
    id: '3',
    name: 'Kids Party Wear',
    price: 1200,
    images: [
      'https://www.kidsbee.in/wp-content/uploads/2023/06/kids-birthday-frock-party-wear.jpg',
    ],
    category: 'Kids',
    colors: ['Pink', 'Yellow'],
    sizes: ['2Y', '4Y', '6Y'],
    description: 'Trendy kids party wear outfit made with premium fabric.',
    inStock: false,
  },
  {
    id: '4',
    name: 'Custom Fabric',
    price: 450,
    images: [
      'https://imagedigital.com.au/wp-content/uploads/2020/01/custom-fabric-print.jpg',
    ],
    category: 'Fabric',
    colors: ['Brown', 'Grey'],
    sizes: [],
    description: 'Custom fabrics sold per meter. Soft & durable.',
    inStock: true,
  },
  {
    id: '5',
    name: 'Denim Jeans',
    price: 1299,
    images: [
      'https://metalhawk.in/cdn/shop/products/MHMJN13422_2.jpg?v=1661461270',
    ],
    category: 'Jeans',
    colors: ['Blue', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    description: 'Classic slim-fit denim jeans for daily wear.',
    inStock: true,
  },
  {
    id: '6',
    name: 'Casual T-Shirt',
    price: 499,
    images: [
      'https://theholistik.com/cdn/shop/files/Mystic-polo-t-shirt-black-1.webp?v=1721985054',
    ],
    category: 'T-Shirt',
    colors: ['White', 'Black', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Soft cotton casual t-shirt for comfort all day long.',
    inStock: true,
  },
  {
    id: '7',
    name: 'Kurti',
    price: 999,
    images: [
      'https://kurtifashion.com/wp-content/uploads/2023/02/Cotton-Long-Kurti-Set-1-sd2fss2.jpg',
    ],
    category: 'Kurti',
    colors: ['Green', 'Maroon'],
    sizes: ['M', 'L', 'XL'],
    description: 'Designer kurti suitable for office and casual wear.',
    inStock: true,
  },
  {
    id: '8',
    name: 'Lehenga Choli',
    price: 3500,
    images: [
      'https://anayadesignerstudio.com/cdn/shop/files/Black-Color-Crop-Top-Lehenga-Choli.webp?v=1714631357',
    ],
    category: 'Lehenga',
    colors: ['Red', 'Golden'],
    sizes: ['S', 'M', 'L'],
    description: 'Traditional lehenga choli with heavy embroidery work.',
    inStock: true,
  },
  {
    id: '9',
    name: 'Men’s Formal Pants',
    price: 1399,
    images: [
      'https://imagescdn.peterengland.com/img/app/product/3/39672053-18969854.jpg',
    ],
    category: 'Pants',
    colors: ['Grey', 'Black'],
    sizes: ['30', '32', '34', '36'],
    description: 'Formal pants ideal for office and meetings.',
    inStock: true,
  },
  {
    id: '10',
    name: 'Printed Scarf',
    price: 299,
    images: [
      'https://5.imimg.com/data5/SELLER/Default/2023/5/305948798/VG/SX/LN/20185625/floral-scarf.jpg',
    ],
    category: 'Accessories',
    colors: ['Multi-color'],
    sizes: [],
    description: 'Lightweight printed scarf for casual styling.',
    inStock: true,
  },
  {
    id: '11',
    name: 'Sports Shoes',
    price: 1799,
    images: ['https://redtape.com/cdn/shop/files/RSO2835_15.jpg?v=1756809360'],
    category: 'Shoes',
    colors: ['White', 'Black'],
    sizes: ['7', '8', '9', '10'],
    description: 'Durable sports shoes for running and training.',
    inStock: true,
  },
  {
    id: '12',
    name: 'Woolen Sweater',
    price: 1599,
    images: [
      'https://cdn.shopaccino.com/ajoobaa/products/handmade-tiger-face-woolen-sweater-for-infants---light-blue-399777_l.jpg?v=594',
    ],
    category: 'Winter Wear',
    colors: ['Navy Blue', 'Brown'],
    sizes: ['M', 'L', 'XL'],
    description: 'Warm woolen sweater for chilly winters.',
    inStock: true,
  },
  {
    id: '13',
    name: 'Casual Shorts',
    price: 699,
    images: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZoDMq0X-Gl6LKowbOZr1Frm8d5atac4dx0Q&s',
    ],
    category: 'Shorts',
    colors: ['Khaki', 'Olive Green'],
    sizes: ['M', 'L', 'XL'],
    description: 'Comfortable cotton shorts for summer days.',
    inStock: true,
  },
  {
    id: '14',
    name: 'Kids Denim Jacket',
    price: 1100,
    images: ['https://m.media-amazon.com/images/I/71949YGch7L._UY1100_.jpg'],
    category: 'Kids',
    colors: ['Blue'],
    sizes: ['3Y', '4Y', '5Y'],
    description: 'Trendy denim jacket for kids to pair with any outfit.',
    inStock: true,
  },
  {
    id: '15',
    name: 'Designer Handbag',
    price: 2200,
    images: [
      'https://img.freepik.com/free-photo/bag-hanging-from-furniture-item-indoors_23-2151073506.jpg?semt=ais_incoming&w=740&q=80',
    ],
    category: 'Accessories',
    colors: ['Black', 'Red'],
    sizes: [],
    description: 'Elegant handbag to complement both ethnic and western wear.',
    inStock: true,
  },
];
